name: Integration tests

on:
  pull_request:

jobs:
  integration-test-with-secrets:
    uses: ./.github/workflows/integration_test_secrets.yaml
    secrets: inherit
  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        args:
          - name: num_units=3, db_from_config
            value: "--test-db-from-config --num-units=3"
          - name: num_units=1, db_from_config
            value: "--test-db-from-config --num-units=1"
          - name: num_units=3, db_from_relation
            value: "--num-units=3"
          - name: num_units=1, db_from_relation
            value: "--num-units=1"
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    with:
      extra-arguments: |
        -m "not (requires_secret)"
        --openstack-rc ./openrc --kube-config ./kube-config
        --screenshot-dir /tmp
        -k ${{ matrix.args.value }}"
      modules: '["test_core", "test_error", "test_upgrade"]'
      pre-run-script: |
        -c "sudo microk8s config > kube-config && \
        sudo microk8s enable registry hostpath-storage"
      setup-devstack-swift: true
      trivy-image-config: trivy.yaml
  required_status_checks:
    name: Required Integration Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - integration-tests
      - integration-tests-with-secrets
    steps:
      - run: echo required checks passed
