name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    with:
      modules: '["test_core", "test_error", "test_upgrade"]'
      extra-arguments: |
        -m "not (requires_secret)" \
        --openstack-rc ${GITHUB_WORKSPACE}/openrc \
        --kube-config ${GITHUB_WORKSPACE}/kube-config \
        --screenshot-dir /tmp
