name: Integration tests

on:
  pull_request:

jobs:
  get-extra-arguments:
    name: Get extra arguments
    runs-on: ubuntu-22.04
    outputs:
      arguments: ${{ env.ARGUMENTS }}
    steps:
      - name: Get extra arguments
        run: |
          echo 'ARGUMENTS<<EOF >> $GITHUB_ENV
          echo ' --openstack-rc ./openrc --kube-config ~/.kube/config' >> $GITHUB_ENV
          echo ' --akismet-api-key ${{ env.TEST_AKISMET_API_KEY }}' >> $GITHUB_ENV
          echo ' --openid-username ${{ env.TEST_OPENID_USERNAME }}' >> $GITHUB_ENV
          echo ' --openid-password ${{ env.TEST_OPENID_PASSWORD }}' >> $GITHUB_ENV
          echo ' --launchpad-team ${{ env.TEST_LAUNCHPAD_TEAM }}' >> $GITHUB_ENV
          echo ' --screenshot-dir /tmp ' >> $GITHUB_ENV
          echo ' ${{ matrix.args.value }} ' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
            " >> $GITHUB_ENV
        env:
          TEST_AKISMET_API_KEY: ${{ secrets.TEST_AKISMET_API_KEY }}
          TEST_OPENID_USERNAME: ${{ secrets.TEST_OPENID_USERNAME }}
          TEST_OPENID_PASSWORD: ${{ secrets.TEST_OPENID_PASSWORD }}
          TEST_LAUNCHPAD_TEAM: ${{ secrets.TEST_LAUNCHPAD_TEAM }}
  integration-tests:
    strategy:
      matrix:
        args:
          - name: num_units=3, db_from_config
            value: "--test-db-from-config --num-units=3"
          - name: num_units=1, db_from_config
            value: "--test-db-from-config --num-units=1"
          - name: num_units=3, db_from_relation
            value: "--num-units=3"
          - name: num_units=1, db_from_relation
            value: "--num-units=1"
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    needs: get-extra-arguments
    with:
      extra-arguments: ${{ needs.get-extra-arguments.outputs.arguments }}
      modules: '["test_core", "test_error", "test_upgrade"]'
      setup-devstack-swift: true
      trivy-image-config: trivy.yaml
  required_status_checks:
    name: Required Integration Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - integration-tests
    steps:
      - run: echo required checks passed
