name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    with:
      modules: '["test_core", "test_error", "test_upgrade"]'
      extra-test-matrix: |
        {
          "args": [
            {
              "name": "num_units=3, db_from_config",
              "value": "--test-db-from-config --num-units=3"
            },
            {
              "name": "num_units=1, db_from_config",
              "value": "--test-db-from-config --num-units=1"
            },
            {
              "name": "num_units=3, db_from_relation",
              "value": "--num-units=3"
            },
            {
              "name": "num_units=1, db_from_relation",
              "value": "--num-units=1"
            }
          ],
          "exclude": [
            {
              "module": "test_error",
              "args": {
                "name": "num_units=3, db_from_config"
              },
            },
            {
              "module": "test_error",
              "args": {
                "name": "num_units=1, db_from_config"
              },
            },
            {
              "module": "test_upgrade",
              "args": {
                "name": "num_units=3, db_from_relation"
              },
            },
            {
              "module": "test_upgrade",
              "args": {
                "name": "num_units=1, db_from_relation"
              },
            }
          ]
        }
      extra-arguments: |
        --openstack-rc ${GITHUB_WORKSPACE}/openrc
        --akismet-api-key ${{ secrets.TEST_AKISMET_API_KEY }}
        --openid-username ${{ secrets.TEST_OPENID_USERNAME }}
        --openid-password ${{ secrets.TEST_OPENID_PASSWORD }}
        --kube-config ${GITHUB_WORKSPACE}/kube-config
        --launchpad-team ${{ secrets.TEST_LAUNCHPAD_TEAM }}
        --screenshot-dir /tmp
        -k ${{ matrix.module }}
        ${{ matrix.args.value }}
