name: Integration tests

on:
  pull_request:

env:
  TEST_AKISMET_API_KEY: ${{ secrets.TEST_AKISMET_API_KEY }}

jobs:
  get-extra-arguments:
    name: Get extra arguments
    runs-on: ubuntu-22.04
    outputs:
      arguments: ${{ env.ARGUMENTS }}
    steps:
      - name: Get extra arguments
        working-directory: ${{ inputs.working-directory }}
        run: |
          args=$(cat <<-END
            --openstack-rc ./openrc \
            --kube-config ~/.kube/config \
            --akismet-api-key ${{ secrets.TEST_AKISMET_API_KEY }}
            --openid-username ${{ secrets.TEST_OPENID_USERNAME }}
            --openid-password ${{ secrets.TEST_OPENID_PASSWORD }}
            --launchpad-team ${{ secrets.TEST_LAUNCHPAD_TEAM }}
            --screenshot-dir /tmp \
            ${{ matrix.args.value }}
          END
          )
          echo "ARGUMENTS=$args" >> $GITHUB_ENV
  integration-tests:
    strategy:
      matrix:
        args:
          - name: num_units=3, db_from_config
            value: "--test-db-from-config --num-units=3"
          - name: num_units=1, db_from_config
            value: "--test-db-from-config --num-units=1"
          - name: num_units=3, db_from_relation
            value: "--num-units=3"
          - name: num_units=1, db_from_relation
            value: "--num-units=1"
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    needs: get-extra-arguments
    with:
      extra-arguments : ${{ needs.get-extra-arguments.outputs.arguments }}
      modules: '["test_core", "test_error", "test_upgrade"]'
      setup-devstack-swift: true
      trivy-image-config: trivy.yaml
  required_status_checks:
    name: Required Integration Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - integration-tests
    steps:
      - run: echo required checks passed
