name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - track/**

jobs:
  test-and-publish-charm:
    needs: integration-tests
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml
    with:
      integration-test-extra-arguments: |
        --openstack-rc ./openrc \
        --kube-config ~/.kube/config \
        --akismet-api-key ${{ secrets.TEST_AKISMET_API_KEY }}
        --openid-username ${{ secrets.TEST_OPENID_USERNAME }}
        --openid-password ${{ secrets.TEST_OPENID_PASSWORD }}
        --launchpad-team ${{ secrets.TEST_LAUNCHPAD_TEAM }}
        --screenshot-dir /tmp \
        ${{ matrix.args.value }}
      trivy-image-config: trivy.yaml
