name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - track/**

jobs:
  integration-test-with-secrets:
    uses: ./.github/workflows/integration_test_secrets.yaml
    secrets: inherit
  integration-test:
    uses: ./.github/workflows/integration_test.yaml
    secrets: inherit
  test-and-publish-charm:
    strategy:
      fail-fast: false
      matrix:
        args:
          - name: num_units=3, db_from_config
            value: "--test-db-from-config --num-units=3"
          - name: num_units=1, db_from_config
            value: "--test-db-from-config --num-units=1"
          - name: num_units=3, db_from_relation
            value: "--num-units=3"
          - name: num_units=1, db_from_relation
            value: "--num-units=1"
    needs: [integration-test, integration-test-with-secrets]
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    with:
      trivy-image-config: trivy.yaml
