name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - track/**

jobs:
  test-and-publish-charm:
    strategy:
      fail-fast: false
      matrix:
        args:
          - name: num_units=3, db_from_config
            value: "--test-db-from-config --num-units=3"
          - name: num_units=1, db_from_config
            value: "--test-db-from-config --num-units=1"
          - name: num_units=3, db_from_relation
            value: "--num-units=3"
          - name: num_units=1, db_from_relation
            value: "--num-units=1"
    needs: integration-tests
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    with:
      integration-test-extra-arguments: |
        -m "not (requires_secret)" \
        --openstack-rc ${GITHUB_WORKSPACE}/openrc \
        --kube-config ${GITHUB_WORKSPACE}/kube-config \
        --screenshot-dir /tmp \
        ${{ matrix.args.value }}
      integration-test-modules: '["test_core", "test_error", "test_upgrade"]'
      integration-test-pre-run-script: |
        -c "sudo microk8s enable registry hostpath-storage
          sudo microk8s kubectl -n kube-system rollout status -w deployment/hostpath-provisioner
          sudo microk8s config > ${GITHUB_WORKSPACE}/kube-config"
      setup-devstack-swift: true
      trivy-image-config: trivy.yaml
